### ISSUE TITLE
keep immigration of triples inside our store

### ISSUE THREAD

**Issue by Simaris** [Simaris/Atomic-Graph#23]
In 
https://github.com/Simaris/Atomic-Graph/blob/f715995a46c533ab95c4ab8a6c471e9354753dea/atomicgraphs/atomic_graph.py#L45
we remove a statement from our graph to include it in our current Atomic Graph
Since we use our own store in
https://github.com/Simaris/Atomic-Graph/blob/f715995a46c533ab95c4ab8a6c471e9354753dea/atomicgraphs/atomic_graph.py#L7
it is more effective to just change the assignment to the new graph inside our own store, to avoid
removing and reincluding it.

**Comment by white-gecko** [comment]
The sketch for a move method is here: #27
